# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 13:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameround',
            name='history',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='socket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
