# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0002_auto_20170501_1309'),
    ]

    operations = [
    ]
