# Generated by Django 3.1.2 on 2020-10-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0008_auto_20170707_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagepool',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='imageranking',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
